<div id="sidebar">
<div class="gadget">
<div class="ddsmoothmenu-v" id="smoothmenu">
<h3>Нашите Продукти</h3>
<ul class="level-1">
<?php foreach ($this->models as $model) { /* @var $model Mad_Script_Generator_Model */?>
	<li><a href="<?php echo $this->url(array('tableName' => $model->tableName))?>"><?php echo $model->modelName;?></a></li>
<?php } ?>
</ul>
</div>
</div>
</div>
<div id="mainbar">
<canvas id="viewport" width="100px" height="100px"></canvas>
</div>

