<?php if($this->isVisibleSideBar !== false) {?>
<div id="sidebar">
<div class="gadget">
<div class="ddsmoothmenu-v" id="smoothmenu">
<div>
	<form action="" id="highlight-type">
	<label>
		<?php echo $this->translate('Filter by model name:')?>
		<input name="model_filter" type="text" id="model_filter" size="13" >
	</label>
	</form>	
</div>
<?php echo $this->navi()->sideBar($this->models);?>
</div>
</div>
</div>
<?php } ?>
<div id="mainbar">
<canvas id="viewport" width="100px" height="100px"></canvas>
</div>

