<div id="sidebar">
<div class="gadget">
<div class="ddsmoothmenu-v" id="smoothmenu">
<h3>Нашите Продукти</h3>
<ul class="level-1">
<?php foreach ($this->models as $model) { /* @var $model Mad_Script_Generator_Model */?>
	<li><a href="<?php echo $this->url(array('tableName' => $model->tableName))?>"><?php echo $model->modelName;?></a></li>
<?php } ?>
</ul>
</div>
</div>
</div>
<div id="mainbar">
<div class="article">
<?php if(($model = $this->model) instanceof Mad_Script_Generator_Model) { /* @var $model  Mad_Script_Generator_Model */?>
	<table>
		<thead>
			<tr>
				<th>Type</th>
				<th>Field name</th>
			</tr>
		</thead>
		<tbody>
<?php foreach ($model->getFields() as $field) { /* @var $field Mad_Script_Generator_Field */?>
		<tr>
			<td>@property <?php echo $field->fieldType?></td>
			<td>$<?php echo $field->fieldName;?></td>
		</tr>
<?php }?>
		</tbody>
	</table>
<?php
}
?>
</div>
<div class="article">
<?php if(($model = $this->model) instanceof Mad_Script_Generator_Model) { /* @var $model  Mad_Script_Generator_Model */?>

<?php 
echo $this->partial('index/_assocsWapper.phtml', array(
	'title'		=> 'Belongs To',
	'assocs'	=> $this->modelBuilder->suggestionsBelongsTo($model)
));

echo $this->partial('index/_assocsWapper.phtml', array(
	'title'		=> 'Has Many',
	'assocs'	=> $this->modelBuilder->suggestionsHasMany($model)
));

echo $this->partial('index/_assocsWapper.phtml', array(
	'title'		=> 'Has Many Through',
	'assocs'	=> $this->modelBuilder->suggestionsHasManyThrough($model)
));

echo $this->partial('index/_assocsWapper.phtml', array(
	'title'		=> 'Has One',
	'assocs'	=> $this->modelBuilder->suggestionsHasOne($model)
));
?>
<?php
}
?>
</div>
</div>

