<?php
/* @var $currentModel Mad_Script_Generator_Model */
$currentModel = $this->currentModel;
?>
<p>
	Model Name: <strong>
					<a 
						href="<?php echo $this->url(array('tableName' => $currentModel->tableName, 'controller' => 'index', 'action' => 'model-assocs'))?>" 
						title="See <?php echo $this->escape($currentModel->modelName)?> relations">
						<?php echo $this->escape($currentModel->modelName);?></a>
				</strong>, 
				Table Name: <strong><?php echo $this->escape($currentModel->tableName);?></strong>
</p>
<table>
	<thead>
		<tr>
			<th>Property</th>
			<th>Type</th>
		</tr>
	</thead>
	<tbody>
<?php 
foreach ($currentModel->getFields() as $field) {
	/* @var $field Mad_Script_Generator_Field */
?>
		<tr <?php if(strpos($field->fieldName, '_id') !== false xor $field->fieldName !== 'id') echo 'style="color:blue;"'?>>
			<td><?php echo $this->escape($field->fieldName) ?></td>
			<td><?php echo $this->escape($field->fieldType) ?></td>
		</tr>
<?php
}
?>	
	</tbody>
</table>

<div>
	<h2>Associations</h2>
	<?php foreach ($currentModel->getAssocs() as $assoc) { /* @var $assoc Mad_Script_Generator_Association_Abstract */?>
		<p><b><?php echo $this->escape($assoc->getType());?></b> <?php echo $this->escape($assoc->getName())?></p>
	<?php }?>
</div>