<?php
/* @var $assoc Mad_Script_Generator_Association_Abstract */
$assoc = $this->assoc;
/* @var $assocHelper Zend_View_Helper_Assoc */
$assocHelper = $this->assoc($assoc);
?>
<form id="assoc-data">
	<?php echo $assocHelper->toInputs(array('options'));?>
	<label>
		Name:
		<input size="<?php echo strlen($assoc->getName());?>" name="assoc[name]" value="<?php echo $assoc->getName();?>" >
	</label>
	<h3>
		<span title="Master model name"><?php echo $assoc->masterModel->modelName; ?></span> : 
		<span title="Association type"><?php echo $assoc->getType(); ?></span> :
		<span title="Association name"><?php echo $assoc->getName(); ?></span>
	</h3>
	<?php if(count($assoc->getAllowedOptionKeys()) > count($assoc->getOptions())) {?>
	<div class="">
		<label>	
			Type:
			<select id="allowed-option-keys">
				<?php 
				foreach ($assoc->getAllowedOptionKeys() as $optionKey) { 
					if(array_key_exists($optionKey, $assoc->getOptions())) continue;
					echo "<option value=\"\">{$optionKey}</option>";
				}
				?>
			</select>
			<a id="add-assoc-opts" href="javascript:;" class="small-button" title="<?php echo $this->translate('Add-option')?>"><?php echo $this->translate('Add-option')?></a>
		</label>
	</div>
	<?php }?>
	<?php if(count($assoc->getOptions())) {?>
	<h3>Association options</h3>
	<table>
		<thead>
			<tr>
				<th>name</th>
				<th>value</th>
				<th>prefill</th>
				<th>action</th>
			</tr>
		</thead>
		<?php foreach ($assoc->getOptions() as $optionKey => $optionValue) {?>
		<tr>
			<td><?php echo $optionKey;?></td>
			<td><input type="text" name="assoc[options][<?php echo $optionKey;?>]" value="<?php echo $optionValue;?>"></td>
			<td>prefill</td>
			<td>
				<a class="small-button" href="javascript:;">Prefil</a>
				<a class="remove-assoc-opt small-button"  href="javascript:;">Remove</a>
			</td>
		</tr>
		<?php }?>
		<thead>
		</thead>
	</table>
	<?php }?>
	<div class="button-set">
		<a id="assoc-options-save" class="button" href="javascript:;">Save</a>
		<a id="assoc-remove" class="button" href="javascript:;">Remove</a>
		<a id="assoc-test" class="button" href="javascript:;">Test</a>
	</div>
</form>
